### ISSUE TITLE
Update required tests in sigstore/community

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/fulcio#1006]
We should require all tests are passing before merging. Need to update https://github.com/sigstore/community/blob/main/github-sync/github-data/repositories.yaml#L449-L452

**Comment by cpanato** [comment]
What are the tests? all of them?

**Comment by haydentherapper** [comment]
All of them, expect I don't know about the two new ones, `codecov/patch` and `codecov/project`. We should omit those for now. I think they might require always increasing codecov, which isn't a reasonable expectation, so we need to figure out how to configure them to be more permissive (for example, allow a ~3% decrease in codecov)
