### ISSUE TITLE
Fulcio 0.1.0 Release Planning

### ISSUE THREAD

**Issue by cpanato** [sigstore/fulcio#106]
**Description**

Release of fulcio v0.1.0

- [x] Modular CA
- [ ] ~Fuclio Client https://github.com/sigstore/fulcio/issues/95~

* planned date
   - 07/Jul/2021

**Comment by lukehinds** [comment]
@cpanato let's shoot for next week, keep your Thursday morning free and I will walk you through the signing process.

**Comment by cpanato** [comment]
@lukehinds added in my agenda!

**Comment by 06kellyjac** [comment]
congrats on tagging `0.1.0` 2 hours ago :tada: 

One thing I noticed is it was tagged without the `v` prefix which is different to the other sigstore projects. Is fulcio going to stay without the `v` prefix or was it a mistake?

**Comment by cpanato** [comment]
> congrats on tagging `0.1.0` 2 hours ago 🎉
> 
> One thing I noticed is it was tagged without the `v` prefix which is different to the other sigstore projects. Is fulcio going to stay without the `v` prefix or was it a mistake?

I think I missed the `v` :(
