### ISSUE TITLE
Docs: clarify the source of the issuer extensions

### ISSUE THREAD

**Issue by woodruffw** [sigstore/fulcio#1145]
**Description**

Fulcio's `oid-info.md` documentation includes docs for two extensions that reference the underlying identity's "issuer": 

> 1.3.6.1.4.1.57264.1.1 | Issuer
This contains the iss claim from the OIDC Identity Token that was presented at the time the code signing certificate was requested to be created. This claim is the URI of the OIDC Identity Provider that digitally signed the identity token. For example: https://oidc-issuer.com.

and:

> 1.3.6.1.4.1.57264.1.8 | Issuer (V2)
This contains the iss claim from the OIDC Identity Token that was presented at the time the code signing certificate was requested to be created. This claim is the URI of the OIDC Identity Provider that digitally signed the identity token. For example: https://oidc-issuer.com.

> The difference between this extension and 1.3.6.1.4.1.57264.1.1 is that the extension value is formatted to the RFC 5280 specification as a DER-encoded string.

When using a "directly" issued OIDC token, this documentation is correct: the `iss` claim is what appears in each extension. 

However, when using a "federated" IdP like Sigstore's own Dex instances, the `iss` claim does _not_ appear in these extensions: instead, the value of `federated_claims.connector_id` appears, which is the value of the _underlying_ IdP's `iss` claim. 

This is arguably an implementation detail, but IMO an important one: clients who obtain an identity token than represents them have a reasonable expectation around being able to _inspect_ that identity token and confirm its claims, and accuracy w/r/t how that token is interpreted will help clients make better use of the Sigstore ecosystem.

CC @jku as well, since his use case is affected by this 🙂 

See https://github.com/sigstore/sigstore-python/pull/635#discussion_r1183968532.

**Comment by woodruffw** [comment]
CC @haydentherapper @znewman01

**Comment by haydentherapper** [comment]
A simple change could be changing "iss claim" to "OpenID Connect provider" or something similar. The use of federated claims is an implementation detail in my opinion. A user who does need to inspect the token would need to understand Dex though, so it's an open question if a client MUST understand this. I'd lean towards no, unless we say that verification of the token before use is a hard requirement.

**Comment by woodruffw** [comment]
That works for me in terms of clarifying the origin, but I wonder where it leaves uses who want to understand the provenance steps between "identity token that represents them" and "certificate bound to their identity" (which I believe is @jku's use case).

I don't think verifying the token before use should be a hard requirement, but I _do_ think there's a valid "sanity checking" use case, which is one we've seen crop up with the Python release managers: they've signed for official Python releases with the wrong identity or issuer a few times now, and we have no way to tell them that or fail before it happens because of the opacity of the identity tokens themselves.

> I don't think a client can know everything, and should depend on a user knowing they're using a federated identity provider and specify where to look for the issuer (maybe have 'iss' be the default)

I might be misunderstanding, but doesn't this produce the same ambiguity? End users might not be super technical (or might be technical, but not familiar with OIDC and federation), so "your Google identity" versus "your Google identity, federated through Sigstore's Dex instance" might be difficult to express to them (especially when they're going "through" Sigstore no matter what). 

Similarly, without guidance about which federated issuer actually lives at `https://oauth2.sigstore.dev/auth`, I'm not sure the clients can provide useful information here on their own: it'd be incorrect (currently) to assume that that issuer will remain Dex, right?

**Comment by haydentherapper** [comment]
In terms of Fulcio, particularly the public instance, I don't think we should expose the difference between federated and non-federated identity - There is trust in Dex, albeit it's still auditable due to certificate transparency. Though it's worth considering if a private instance would want to make a different decision and distinguish between the two. I'd argue no because of transparency and probably because the private provider is run within the same trust domain as the private Fulcio instance.

As for the client, my comment was more about that there are many mappings between claims to certificate extensions. Do we want a client to have that mapping? For example, if you want to verify CI claims are present in an extension, you need to know the mapping between claim per CI platform and extension. Though it's a well defined mapping, so there's no technical reason why you couldn't. 

Correct, I don't think a client should always assume Dex. My comment was that it's not known which fields will contain the issuer, so you need to rely on the user to specify them. Or you could simply assume it's either 'iss' or when 'iss'= https://oauth2.sigstore.dev/auth, then it's the federated claim.

**Comment by haydentherapper** [comment]
> so just to be sure: "client" here refers to a sigstore client library/CLI? And user refers to a human user or an application using the sigstore client library?

Correct. The user is the entity that will know which claims are relevant for verification. So more accurately, the user is the verification policy.

> I shouldn't have to understand dex or federated_claims or connector_ids, I should be able to verify that signer identity that will be used in the signing certificate is ABC with issuer XYZ.

I agree that a user shouldn't have to know anything about Dex. If not the user, then the client must. This comes back to a conversation we've had for Cosign, separating the public good instance workflow from private workflows. I think it's fine if the client by default handles the case of using the Sigstore Dex instance, knowing that the issuer comes from a different field.

**Comment by woodruffw** [comment]
> I agree that a user shouldn't have to know anything about Dex. If not the user, then the client must. This comes back to a conversation we've had for Cosign, separating the public good instance workflow from private workflows. I think it's fine if the client by default handles the case of using the Sigstore Dex instance, knowing that the issuer comes from a different field.

I think that resolves the issue on the `sigstore-python` side as well! Thanks @haydentherapper!

I'll also open a PR for the Fulcio docs with the change suggested in https://github.com/sigstore/fulcio/issues/1145#issuecomment-1533691566 in a bit.

**Comment by woodruffw** [comment]
#1158 includes the doc changes: I've removed the language implying that `iss` is always the issuer extension value, and replaced it with a more narrow claim about non-federated tokens.
