### ISSUE TITLE
Basic Logging/Monitoring

### ISSUE THREAD

**Issue by dlorenc** [sigstore/fulcio#13]
Same stuff we have in rekor:
- [ ] Structured logs to stdout, ingested into stackdriver with working error levels
- [ ] Metrics on latency, new certs issued, etc.
- [ ] Alerts on all of the above.
- [ ] Test probers running against prod

**Comment by haydentherapper** [comment]
Can we keep this open to track adding monitoring? For example, https://github.com/sigstore/fulcio/pull/267 is adding support for Prometheus

**Comment by lukehinds** [comment]
Start one fresh @haydentherapper and add items you feel should be tracked (and tag me pls)

**Comment by haydentherapper** [comment]
Planning to do so shortly! I'm working on a doc on the remaining tasks I think we need to do for productionization (not all of which I think need to block 1.0)

**Comment by haydentherapper** [comment]
As we chatted about in today's meeting, it'd be best to wait on the task list until we know who is running the production instance longterm.
