### ISSUE TITLE
Issue while running sigstore locally

### ISSUE THREAD

**Issue by VikramPunnam** [sigstore/fulcio#1427]
Hi,
I have setup sigstore locally as suggested by https://blog.sigstore.dev/a-guide-to-running-sigstore-locally-f312dfac0682/

Im trying to sign the image with cosign and the OIDC is keycloak. 

but getting below error. Can anyone help me to resolve.

**Command used:**
cosign sign --fulcio-url=https://dev-fulcio.xxxx.com --oidc-issuer=https://qa-keycloak.xxxx.local/realms/sigstore --oidc-client-id='sigstore' --oidc-client-secret-file='secret' --rekor-url=https://dev-rekor.xxxx.com qa-harbor.xxxx.local/eks/alpine:1.27.4

**Error log:**
2023-10-19T11:34:36.572Z	ERROR	server/error.go:45	returning with error	{"requestID": "eriw8uOY", "code": "Internal", "clientMessage": "Error entering certificate in CTL", "error": "got HTTP status \"404 Not Found\""}
53
github.com/sigstore/fulcio/pkg/server.handleFulcioGRPCError

**Comment by haydentherapper** [comment]
Make sure your Fulcio instance is configured to point to a local certificate transparency log, configurable with `--ct-log`, or set the flag to `--ct-log=""` to skip this.

**Comment by VikramPunnam** [comment]
hi @haydentherapper , thanks for your response.

I have modified the --ct-log-url to the local ctlog server. That issue resolved. but now Im getting different error.

(base) [ec2-user@mum1bado1q04 sigstore]$ cosign sign --fulcio-url=https://dev-fulcio.xxxx.com --oidc-issuer=https://qa-keycloak.xxxx.local/realms/sigstore --oidc-client-id='sigstore' --oidc-client-secret-file='secret' --rekor-url=https://dev-rekor.xxxx.com qa-harbor.xxxx.local/eks/alpine:1.27.4
Generating ephemeral keys...
Retrieving signed certificate...

        The sigstore service, hosted by sigstore a Series of LF Projects, LLC, is provided pursuant to the Hosted Project Tools Terms of Use, available at https://lfprojects.org/policies/hosted-project-tools-terms-of-use/.
        Note that if your submission includes personal data associated with this signed artifact, it will be part of an immutable record.
        This may include the email address associated with the account with which you authenticate your contractual Agreement.
        This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later, and is subject to the Immutable Record notice at https://lfprojects.org/policies/hosted-project-tools-immutable-records/.

By typing 'y', you attest that (1) you are not submitting the personal data of any other person; and (2) you understand and agree to the statement and the Agreement terms at the URLs listed above.
Are you sure you would like to continue? [y/N] y
error opening browser: exec: "xdg-open": executable file not found in $PATH
Go to the following link in a browser:

         https://qa-keycloak.xxxx.local/realms/sigstore/protocol/openid-connect/auth?access_type=online&client_id=sigstore&code_challenge=-KR9yusl4D0N3moXJ3ClU5U45f6W5MrdGtyso9IgaGM&code_challenge_method=S256&nonce=2X1oX5BADzSZiBCsJG18JNH4Qaf&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid+email&state=2X1oX579ZuxXyfObI45pptXzdvi
Enter verification code: 9378acc7-60a6-4246-bc19-5492dff84127.4bc8dd58-cb36-4667-ba1b-7249e5c32fd5.c495c10d-393a-41d1-b58e-6759f95828ed

Error: signing [qa-harbor.xxxx.local/eks/alpine:1.27.4]: getting signer: getting key from Fulcio: retrieving cert: POST https://dev-fulcio.xxxx.com/api/v1/signingCert returned 503 Service Unavailable: "upstream connect error or disconnect/reset before headers. reset reason: connection termination"

**Comment by haydentherapper** [comment]
This sounds like an issue with your local environment.
