### ISSUE TITLE
help calls itself `fulcio-server` but the release is `fulcio`

### ISSUE THREAD

**Issue by 06kellyjac** [sigstore/fulcio#152]
**Question**

`--help` calls itself `fulcio-server` but the release is `fulcio`, which should it be?

we're currently renaming it `fulcio-server` in nixpkgs
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/fulcio/default.nix#L21

**Comment by cpanato** [comment]
I will fix that in the next release
