### ISSUE TITLE
Codefresh OIDC provider support

### ISSUE THREAD

**Issue by ilia-medvedev-codefresh** [sigstore/fulcio#1592]
Codefresh has recently added support for OIDC in pipelines: 
https://codefresh.io/docs/docs/integrations/oidc-pipelines
For integration with Sigstore Codefresh OIDC provider needs to be added to supported providers in Fulcio.

**Comment by haydentherapper** [comment]
@ilia-medvedev-codefresh The configuration has been rolled out to staging, https://fulcio.sigstage.dev. If you're using Cosign, you can follow https://docs.sigstore.dev/system_config/public_deployment/#staging-instance to set up the environment to test against. 

Let me know if you get a certificate issued properly and we'll move forward with enabling this in prod. If you can paste the cert here too so we can double check all values are as expected?

**Comment by ilia-medvedev-codefresh** [comment]
Hi @haydentherapper ,

Thank you! I can confirm everything works. 

Here is the resulting cert:
`-----BEGIN CERTIFICATE-----
MIIEcDCCA/agAwIBAgIUamGH0xq1+PftOXrKGS/l9dd4ff8wCgYIKoZIzj0EAwMw
NzEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MR4wHAYDVQQDExVzaWdzdG9yZS1pbnRl
cm1lZGlhdGUwHhcNMjQwNDA3MTQzNTM2WhcNMjQwNDA3MTQ0NTM2WjAAMFkwEwYH
KoZIzj0CAQYIKoZIzj0DAQcDQgAEWbDnGLIJR9I1nTVjQ6h9Lw9uDMsy1NozSH9S
7WuqA2iBKsSKq6+yCrEij05Elhl4K/YN+rcBW5Cf4ZYhF9MC76OCAxUwggMRMA4G
A1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUgRBi
sqLiZOVjLHgdB/xaRRYmgsswHwYDVR0jBBgwFoAUcYYwphR8Ym/599b0BRp/X//r
b6wwewYDVR0RAQH/BHEwb4ZtaHR0cHM6Ly9nLmNvZGVmcmVzaC5pby9pbGlhLWNv
ZGVmcmVzaC9vaWRjLXRlc3Qvb2lkYy10ZXN0LTI6NjI4YTgwYjY5M2ExNWMwZjlj
MTNhYjc1LzY1ZTZkNTU1MWU0N2U1YmMyNDNjYTkzZjAnBgorBgEEAYO/MAEBBBlo
dHRwczovL29pZGMuY29kZWZyZXNoLmlvMCkGCisGAQQBg78wAQgEGwwZaHR0cHM6
Ly9vaWRjLmNvZGVmcmVzaC5pbzBFBgorBgEEAYO/MAEJBDcMNWh0dHBzOi8vZy5j
b2RlZnJlc2guaW8vYnVpbGQvNjYxMmFhNzZkNDU5OWM5ODhiY2Q3MTNmMBYGCisG
AQQBg78wAQsECAwGSHlicmlkMEEGCisGAQQBg78wAQwEMwwxaHR0cHM6Ly9naXRo
dWIuY29tL2lsaWEtbWVkdmVkZXYtY29kZWZyZXNoL2Z1bGNpbzAUBgorBgEEAYO/
MAEOBAYMBG1haW4wTQYKKwYBBAGDvzABEgQ/DD1odHRwczovL2cuY29kZWZyZXNo
LmlvL2FwaS9waXBlbGluZXMvNjVlNmQ1NTUxZTQ3ZTViYzI0M2NhOTNmMEUGCisG
AQQBg78wARUENww1aHR0cHM6Ly9nLmNvZGVmcmVzaC5pby9idWlsZC82NjEyYWE3
NmQ0NTk5Yzk4OGJjZDcxM2YwgYoGCisGAQQB1nkCBAIEfAR6AHgAdgArMLzcaIjJ
4uHYJiledB9IOTGWAvKcM8teQ0D+sqyGegAAAY64/HYGAAAEAwBHMEUCIQD7/blg
zE9eJHtTm8SjfMB33DsG7Ch9bcdKLmvo7Ww3pAIgY8oZu9SnhxL0/+qnxd+QX9ei
X/AO5M1CajOhSln6piQwCgYIKoZIzj0EAwMDaAAwZQIxANurrnGpm7HX7ufFupXE
mrvvWFCi+ld/KuLi7FB9Z3IH4VXZmc/5ZaT9+1lG00zIUwIwTrnZoyy573/Qf961
iw39HXcKjX0UJFj80Fo5t7Msr6kvIVeBdaYFP3lII/ErnobG
-----END CERTIFICATE-----`

**Comment by haydentherapper** [comment]
@ilia-medvedev-codefresh rolling out to prod now!
