### ISSUE TITLE
How can I get the CT log?

### ISSUE THREAD

**Issue by S1eepeng** [sigstore/fulcio#1672]
**Question**
As shown in docs.sigstore.dev,artifact log and identity log should be recorded to an immutable record and support public audit.
The identity log (or CT log) should be get and monitored in ctfe.sigstore.dev/<year>,but this website seems inaccessible?So how can I monitor published certificates？
Thank you much for your reply.

**Comment by haydentherapper** [comment]
Good question! The CT log URLs are suffixed with a unique identifier for each log shard. The source of truth for the logs is accessible on our log list file https://github.com/sigstore/root-signing/blob/main/targets/trusted_root.json#L59-L89.

If you wanted to monitor the log, the latest log is `ctfe.sigstore.dev/2022`. At some point, we may create another log shard which will be published to the `trusted_root.json` file.

**Comment by S1eepeng** [comment]
Thanks for your reply!
In fact,when I tried to visit https://ctfe.sigstore.dev/test or https://ctfe.sigstore.dev/2022,I only get HTTP ERROR 404,but my internet seems to be fine.Are there any other rules to visit these websites?

**Comment by haydentherapper** [comment]
The logs are accessible via the API defined in https://datatracker.ietf.org/doc/html/rfc6962. You can use a client like https://github.com/google/certificate-transparency-go/tree/master/client to access them as well.
