### ISSUE TITLE
cosign in Github Actions returns "There was an error processing the identity token"

### ISSUE THREAD

**Issue by r0mant** [sigstore/fulcio#1769]
**Description**

We use cosign to sign images as a part of our release workflow running in Github Actions and starting this week it stopped working with the following error:

`
Error: signing [public.ecr.aws/xxx/xxx@sha256:123xxx]: getting signer: getting key from Fulcio: retrieving cert: POST https://fulcio.sigstore.dev/api/v1/signingCert returned 400 Bad Request: "{\"code\":3, \"message\":\"There was an error processing the identity token\", \"details\":[]}"
`

Inspecting the source code this error is most certainly caused by OIDC token validation: https://github.com/sigstore/fulcio/blob/ddc294bd39bfd46a7c52b8feac41bb8ca91a4bca/pkg/server/grpc_server.go#L84-L88

Nothing changed on our side in these workflows and we've reached out to Github support as well but were there any recent changes in Fulcio that could've caused this issue with auth via OIDC tokens? Unfortunately, the real error is not returned to the client and only logged in server logs so we can't see what the actual issue validating the token is.

In case this helps, one of the images failing in this way is `public.ecr.aws/gravitational/teleport-kube-agent-updater`.

**Version**

We use `sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0` in our Github Actions.

**Comment by haydentherapper** [comment]
Hey @r0mant, sorry about that, I think we've identified the root cause and are rolling out a change right now. The issue was with a recent change to how we configure CI provider support. I'll let you know once it's rolled out, if you'd be able to confirm it's working after the rollout, that would be very helpful.

**Comment by r0mant** [comment]
@haydentherapper Thank you for quick response! Yep, we're using Github Enterprise Cloud.

**Comment by haydentherapper** [comment]
@r0mant, can you retrigger a workflow that signs your container again and let me know if it works?

**Comment by r0mant** [comment]
@haydentherapper All green now, thank you so much for the fast turnaround! 🙌

**Comment by mveytsman** [comment]
Hi @haydentherapper I am getting this error message using self-hosted GitLab. Is it possible that I'm hitting a related issue?

**Comment by haydentherapper** [comment]
@mveytsman Was it working previously? There are a fixed set of Gitlab instances supported by the public Fulcio instance as seen [here](https://github.com/sigstore/fulcio/blob/main/config/identity/config.yaml#L40-L60) and [here](https://github.com/sigstore/fulcio/blob/main/config/identity/config.yaml#L87-L93). Looking through the server logs, I see an instance of a self-hosted Gitlab instance `gitlab.<domain>.io` with an error `failed to match issuer URL from token with any configured providers`.

**Comment by mveytsman** [comment]
@haydentherapper Thanks for the quick response - no I'm just trying to set it up for the first time. And I think you got the instance right (gitlab.qubridge.io)

Seeing as how that's not on the list of public instances, I'm not sure how to proceed. I've also been following the details I found here: https://github.com/sigstore/cosign/issues/2730

I understand this issue might not be the best place to address this, but any help or pointing me to the right place you can do would be much appreciated!

Thank you
