### ISSUE TITLE
Fulcio should return root CA and client in a more useful format

### ISSUE THREAD

**Issue by lukehinds** [sigstore/fulcio#190]
Currently fulcio returns the cert chain as two whitespace separated blocks.

It would be more useful to folks if we returned in json:

```
{
  "rootca": {-----BEGIN CERTIFICATE-----abcde...},
  "client_cert": {-----BEGIN CERTIFICATE-----abcde...},
}
```

**Comment by haydentherapper** [comment]
Luke, can I close this? I think this is now outdated with the gRPC work.
