### ISSUE TITLE
Release 1.0 planning

### ISSUE THREAD

**Issue by lukehinds** [sigstore/fulcio#191]
The MVP is established now and other projects are leveraging fulcio, so its time to plan for 1.0

- [x] #194
- [x] #187
- [x] #195
- [x] #13 

cc @cpanato

**Comment by cpanato** [comment]
same from rekor:

I would like to add a cloudbuild + goreleaser when we release Fulcio

then I have some questions:

1. We will use the same KMS key that we use to sign `cosign`? or we create another?
2. To push the data to the Rekor server how can we do that in an automated fashion way? there is any guide? or we just don't do it at this time?

@dlorenc @lukehinds @dekkagaijin

**Comment by mattmoor** [comment]
The googlecs stuff needs to move to the 1.0 API

**Comment by jdolitsky** [comment]
Should probably lock down the configuration prior to 1.0: https://github.com/sigstore/fulcio/issues/304

**Comment by nsmith5** [comment]
Not 100% configuration change should be 1.0 blocker. If only because it seems like it might take some time to finish up a refactor. I discussed it a bit here: https://github.com/sigstore/fulcio/issues/304#issuecomment-1019345636

**Comment by lukehinds** [comment]
I have been thinking the same. fuclio has been operating in a stable manner for a while now. I will freeze the milestone and we can look at closing the release.

cc @cpanato

**Comment by cpanato** [comment]
if need to change any configuration, maybe we can do that now and make a pre-release with deprecations and then plan the 1.0 removing the deprecations.

**Comment by lukehinds** [comment]
@cpanato as I understand, it won't be a change of flags or a non backwards compatible change. 

At the moment we have a pattern of folks adding to 1.0, but not able to do the work and so we are seeing 1.0 pushed back and a moving target. For me the most important role of fulcio is the public good instance and what we have at present, which although I am sure can be improved over time, is currently functioning well.

**Comment by cpanato** [comment]
ahh got it, i think i misunderstood :(

**Comment by haydentherapper** [comment]
Everything here has been completed. Work is tracked here - https://github.com/orgs/sigstore/projects/5/views/1
