### ISSUE TITLE
Migrate GCP CA to 1.0

### ISSUE THREAD

**Issue by lukehinds** [sigstore/fulcio#195]
Google has now implemented 1.0 with various changes, this means we need to update the googleca code to 1.0

**Comment by bobcallaway** [comment]
@dlorenc do we need to move to a new KMS object in GCP (and do this before the signing session this Friday)?

**Comment by dlorenc** [comment]
We're still using the CA. We can create a new one whenever, but we'll need to be careful with the migration since the root is still pinned in cosign.

**Comment by lukehinds** [comment]
We also need to be mindful of the public instance (and their chosen implementation), although we don't know what that looks like just yet.

**Comment by nsmith5** [comment]
I think this is done now right? I think v1beta1 support just got deprecated as well

**Comment by dlorenc** [comment]
Yup!
