### ISSUE TITLE
Figure out how to support other OIDC providers

### ISSUE THREAD

**Issue by dlorenc** [sigstore/fulcio#22]
There's no canonical mapping of email address to authoritative OIDC provider. This means we can't just let users provide their own configs. For example:

* Someone could stand up their own OIDC instance and issue tokens for any email address, if we trusted all providers blindly we would mis-issue certs.
  * We would be able to detect this and recover from it with transparency logs, but it's still not good.

So, we'll need a way to add OIDC providers **that we trust** one by one to cover most email addresses.

For users that truly want to run their own email systems, we have a couple options:

- ACME-style DNS challenges on MX records to ensure the user has control of email routing for that domain
- Email-based challenges - we send a token, they enter it. Email is wildly insecure, but if we want to support complete federation we don't have too many other options. This is hard to automate as well.
- Our own login system
  - I don't love this idea, but it does give us flexibility. Login to sigstore with an account (OIDC is fine too), and strengthen that account with other challenges (similar to keybase). We can verify access to an email address here however we need to once a week, month, etc. manually, then automatically issue certs using our own oauth challenges.

**Comment by bobcallaway** [comment]
Note here for myself and others: the `email_verified` claim simply notes that when verification was requested, the provider was able to successfully verify ownership of the email account... however this could have been quite some time in the past and as such isn't sufficient to trust a claim.

**Comment by cpanato** [comment]
fixed by https://github.com/sigstore/fulcio/pull/105

closing
