### ISSUE TITLE
Malformed collection name: 'caPools/certificateAuthorities/certificates'

### ISSUE THREAD

**Issue by dirien** [sigstore/fulcio#238]
**Question**
Hi, i started the fulcio server via the docker-compose file. I create a CA at google but i get following error message:

```bash
desc = Malformed collection name: 'caPools/certificateAuthorities/certificates'
```

config looks like this:

```yaml
..
      "--ca=googleca",
      "--gcp_private_ca_parent=projects/minectl-fn/locations/europe-west3/caPools/dirien/certificateAuthorities/20211110-nmq-zqi",
      "--ct-log-url=http://ct_server:6962/test",
      # Uncomment this for production logging
...
```

Any hints, of what I am doing wrong? The ~/.config/gcloud is also mapped. Actually everything is set up as described in the DEVELOPMENT.md

Thanks for your feedback.

**Comment by haydentherapper** [comment]
Hey @dirien, this is because Fulcio previously didn't support the GCP CA Service V1 API, it only supported the beta API. With https://github.com/sigstore/fulcio/pull/218, there is now support for the V1 API. You'll need to set `--gcp_private_ca_version`.

**Comment by dirien** [comment]
kk @haydentherapper thanks for the feedback!

**Comment by haydentherapper** [comment]
We also removed this flag recently since we dropped support for the GCP CA Service beta API.
