### ISSUE TITLE
flag provided but not defined: -trimpath

### ISSUE THREAD

**Issue by maltfield** [sigstore/fulcio#251]
Build fails with the following error

```
user@disp3886:~/fulcio$ make
cd hack/tools; go build -trimpath -tags=tools -o /home/user/fulcio/hack/tools/bin/swagger github.com/go-swagger/go-swagger/cmd/swagger
flag provided but not defined: -trimpath
usage: go build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [Makefile:112: /home/user/fulcio/hack/tools/bin/swagger] Error 2
user@disp3886:~/fulcio$ 
```

Steps to reproduce on Debian 10

```
sudo apt-get install golang
git clone https://github.com/sigstore/fulcio.git
cd fulcio
make
```

## Additional context

```
user@disp3886:~$ cat /etc/issue
Debian GNU/Linux 10 \n \l

user@disp3886:~$ uname -a
Linux disp3886 5.4.156-1.fc25.qubes.x86_64 #1 SMP Fri Oct 29 02:51:34 CEST 2021 x86_64 GNU/Linux
user@disp3886:~$ go version
go version go1.11.6 linux/amd64
user@disp3886:~$ 
```

**Comment by maltfield** [comment]
It does appear to compile in Debian 11. At least I had success with executing the following to build it in a Debian 11 (bullseye) docker container

```
sudo su -
apt-get install docker.io
export DOCKER_CONTENT_TRUST=1
docker run --rm -it --entrypoint /bin/bash debian:bullseye

apt-get update
apt-get install -y git build-essential golang
git clone https://github.com/sigstore/fulcio.git
cd fulcio
make
```

**Comment by bobcallaway** [comment]
`- trimpath` was added in [Go 1.13](https://go.dev/doc/go1.13) and you're building with 1.11. Per the go.mod, we assume a minimum of 1.16 for Fulcio so I think you'll need to upgrade your golang install before proceeding.

**Comment by maltfield** [comment]
Unfortunately, the latest version of Go in:

1. Debian 10 is 1.11 https://packages.debian.org/buster/golang
2. Debian 11 is 1.15 https://packages.debian.org/bullseye/golang

...so it appears that fulcio is too bleeding-edge for Debian 10 native :(

**Comment by maltfield** [comment]
Unfortunately, I had a different build error in Debian 11. I submitted a distinct issue for that one:

 * https://github.com/sigstore/fulcio/issues/253
