### ISSUE TITLE
make error: package embed is not in GOROOT

### ISSUE THREAD

**Issue by maltfield** [sigstore/fulcio#253]
Running `make` in Debian 11 fails with the following error

```
root@194ee81f190b:/fulcio# make
...
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
pkg/generated/restapi/configure_fulcio_server.go:34:2: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)
make: *** [Makefile:66: fulcio] Error 1
root@194ee81f190b:/fulcio# 
```

This can be reproduced with the following commands:

```
sudo su -
apt-get install docker.io
export DOCKER_CONTENT_TRUST=1
docker run --rm -it --entrypoint /bin/bash debian:bullseye-slim

apt-get update
apt-get -y install build-essential golang git

cat /etc/issue
uname -a
go version

git clone https://github.com/sigstore/fulcio.git
cd fulcio
make
```

### Context

```
root@194ee81f190b:/fulcio# cat /etc/issue
Debian GNU/Linux bullseye/sid \n \l

root@194ee81f190b:/fulcio# uname -a
Linux 194ee81f190b 5.4.156-1.fc25.qubes.x86_64 #1 SMP Fri Oct 29 02:51:34 CEST 2021 x86_64 GNU/Linux
root@194ee81f190b:/fulcio# go version
go version go1.15.9 linux/amd64
root@194ee81f190b:/fulcio# 
```

**Comment by Mythra** [comment]
This is a similar issue to the one you last posted. [Golang Embed was added in 1.16](https://tip.golang.org/doc/go1.16#library-embed) which is newer than your go version of 1.15. This also lines up with the go version in go.mod being 1.16 which is the expected version to build with.

I see 3 ways you can get this now without any changes (I won't comment on whether the project should be using 1.16 at all):

  1. You could download the fulcio release and verify the signature <https://github.com/sigstore/fulcio/releases>. Golang builds a static binary so there should be no problem running it.
  2. Get the latest golang version outside of debians repositories which are older: <https://go.dev/doc/install>
  3. Build the binary on a host/docker container with a modern version of go in its repositories, and copy the resulting static binary over,

**Comment by bobcallaway** [comment]
+1 to what @Mythra said above - fulcio requires a [minimum of go 1.16](https://github.com/sigstore/fulcio/blob/f2e24d2c780fbeee950024873592e18e2c6b67dc/go.mod#L3) to build.
