### ISSUE TITLE
What are the main Use cases for Fulcio?

### ISSUE THREAD

**Issue by maorkuriel** [sigstore/fulcio#294]
I have read this blog post https://chainguard.dev/posts/2021-11-12-fulcio-deep-dive, and the technology is impressive.

With that said, I am trying to map specific usage for this tool in cloud-native environments, if there are??
Would you mind listing the primary use cases that you see this OSS address? 
What is the problem that it was meant to solve? 

I appreciate any help you can provide.

**Comment by dlorenc** [comment]
Fulcio is a bit hard to use by itself - it generally needs tooling to help fit it into existing workflows. For cloud native applications, the most relevant would probably be to use Fulcio through cosign for keyless container signing and verification.

Does that help at all?

**Comment by maorkuriel** [comment]
Yes, this helps.
Thank you.
