### ISSUE TITLE
Replace `ephemeralca` in cosign e2e tests with `fileca`

### ISSUE THREAD

**Issue by nsmith5** [sigstore/fulcio#301]
**Description**

In the `fileca` PR we dicussed using `fileca` instead of `emphemeralca` in e2e tests.

**Comment by nsmith5** [comment]
@mattmoor is this still desired? I know there is that API endpoint that returns the CA certifficate chain now and wasn't sure if that covered the same need..

**Comment by mattmoor** [comment]
I think we probably do.  cc @vaikas for thoughts

**Comment by vaikas** [comment]
Yeah, that would make the most sense to me, because indeed we now have a way to programmatically fetch the cert being used. Which led me to questioning the need for ephemeralca in the first place anymore, but that's another discussion :)
