### ISSUE TITLE
Consider switching the --fileca-key-passwd to not contain pwd but point to file containing the pwd

### ISSUE THREAD

**Issue by vaikas** [sigstore/fulcio#303]
In #280 support for keys/cert from the disk became available, thank you @nsmith5 for that! I've been playing with it for a bit and it works exactly as advertised, but I'm curious (before it gets too widely used and have to worry about migration strategy, etc.) if we might want to consider changing this flag:

```
fileca-key-passwd
```

To not be a flag that has the password, but instead it's pointer to file containing the password, like the other newly introduced flags. So, you'd write the password to file, and the flag would point to the file containing the password.

There's couple of reasons why I thought this might be useful.

1. in K8s it's easier to mount the secret into a file than a flag. You can mount it also into an env variable, and then bind it to a value in the args (flag), but since the others are files, well, seems more consistent also.
2. This I think is actually more important, since there has been talk about watching changes to the files, so even if we were to watch the underlying filesystem for changes, we're not really able to update the flag. If we however mounted the password to file, then we could watch changes to that file as well (races, mumble...) but still more doable.

**Comment by n3wscott** [comment]
Or like docker and ko do and take the password from stdin?

**Comment by nsmith5** [comment]
Perhaps we should do all three if it makes sense?

- `--fileca-key-passwd` as a literal
- `--fileca-key-passwd-file` as a file containing the password
- `--fileca-key-passwd-stdin` from stdin?

I like options for operators (know this world a lot), but I can see there may be a different security posture (know this world less and am learning) for each.

> (races, mumble......)
I think we ought to be already on the race condition front. The watcher tries to load key-pairs but if there is a mismatch it just bails and waits for everything to match up. If you add the password file the same will be true: the cert-key pair will only rotate once the password, key and certificate file all match each other (though we'll check to see if they're matching on every write to any of the three)

**Comment by n3wscott** [comment]
I just wrote this code for ... something else. Let me look at upstreaming a version of it here too.

**Comment by haydentherapper** [comment]
Closing this issue, since we are only using the file CA for testing and it's been working well. @n3wscott if you have code you wanted to commit for this, feel free to reopen when you do.
