### ISSUE TITLE
Consider supporting multiple CTLogs

### ISSUE THREAD

**Issue by vaikas** [sigstore/fulcio#310]
**Description**
Currently we support one CTLog where SCT is then returned from. It might be useful in the future to support multiple ones. Besides the obvious need to modify code, just curious if we may want to consider at least allowing the API here:
https://github.com/sigstore/fulcio/blob/main/pkg/api/client.go#L31

Also copied here in case links shift:
```
type CertificateResponse struct {
	CertPEM  []byte
	ChainPEM []byte
	SCT      []byte
}
```

To be able to return multiple SCT, and we could further restrict the current api to say that it will only return 0 atm.

Brought this up 2022-01-04 meeting and it was deemed that we may want to look into this, from a quick look didn't see an issue, so here it is :)

There also has been some further discussion in the past so mayhaps we can gather those thoughts here, or pointers to them in case folks want to chime in / follow along.

**Comment by haydentherapper** [comment]
https://github.com/sigstore/fulcio/pull/507 will solve this since an SCT list will be embedded in certificates.

**Comment by vaikas** [comment]
Nice!

**Comment by haydentherapper** [comment]
Closing issue, as we now support embedding SCT lists in certificates.
