### ISSUE TITLE
Remove the v1beta1 GCP CA API

### ISSUE THREAD

**Issue by dlorenc** [sigstore/fulcio#342]
This was left in place for the migration, I don't think we have any use case for it anymore.

cc @n3wscott @haydentherapper - any reason to keep it? Could be a good starter issue.

**Comment by n3wscott** [comment]
Yeah delete it!

**Comment by haydentherapper** [comment]
Agreed, no reason to keep it! Beta is no longer supported.

**Comment by znewman01** [comment]
I can do this

**Comment by znewman01** [comment]
Not sure what typical deprecation policy is, since we're pre-1.0. I prepared 2 PRs: #348 (deprecate) and #349 (remove). I suppose if we don't care to deprecate this formally you can just merge both.

**Comment by znewman01** [comment]
> just merge both

Err, I meant just merge #349 since it has both commits in it (otherwise you'll get both release notes at once).
