### ISSUE TITLE
Add support for rate limiting in fulcio

### ISSUE THREAD

**Issue by priyawadhwa** [sigstore/fulcio#365]
We can set up rate limiting based on IP address for Fulcio. (also mentioned in https://github.com/sigstore/fulcio/issues/193#issuecomment-994247492)

**Comment by haydentherapper** [comment]
We can either add rate limiting in the service (possibly leveraging this [rate limiting library](https://github.com/uber-go/ratelimit)) or in Nginx configs ([instructions](https://www.nginx.com/blog/rate-limiting-nginx/)). I prefer to implement this in Nginx, to avoid a misbehaving client from ever hitting the service. However, it may also be valuable to implement this in the service for those who want to stand up their own Sigstore infrastructure without Nginx, and still get rate limiting/

**Comment by priyawadhwa** [comment]
Let's add it to nginx as the GA goal, and we can implement it in the service itself as a P1?

**Comment by haydentherapper** [comment]
Something to consider - Github Actions will likely generate orders of magnitude more traffic than individuals. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses discusses how to dynamically fetch IP addresses.

**Comment by haydentherapper** [comment]
Completed
