### ISSUE TITLE
Break down mega-README into bite size articles under /docs

### ISSUE THREAD

**Issue by nsmith5** [sigstore/fulcio#372]
**Description**

The README has sort of just grown organically over time and I think its high time it gets broken down into more focused documents under something like a `/docs` folder. We can link to that folder form the README so the information is still easily discoverable, but keep the copy in the README a tighter narrative about what Fulcio does. The focus here would be leaning towards contributors primarily as the end-user documentation lives at https://docs.sigstore.dev which lives over here https://github.com/sigstore/sigstore-website.

**Comment by dlorenc** [comment]
Big +1 to this! For GitHub "SEO" it's usually good to have a small blurb/diagram/picture targeted to end-users "above the fold" in the README, but the rest of the end-user stuff should move to the docs website and this can stay contributor focused.

**Comment by nsmith5** [comment]
Yes absolutely!

**Comment by endorama** [comment]
Ok so first step is breaking down the README, then I'll start moving things around.

**Comment by nsmith5** [comment]
Readme is a lot more reasonable now. Closing this
