### ISSUE TITLE
Build failure on OpenBSD: ld: error: unable to find library -ldl

### ISSUE THREAD

**Issue by tstromberg** [sigstore/fulcio#375]
When running `go test .`, `go install`, or any other build step on OpenBSD:

```
# github.com/miekg/pkcs11                                                                                                          
ld: error: unable to find library -ldl                                                                                             
cc: error: linker command failed with exit code 1 (use -v to see invocation)                                                       
FAIL    github.com/sigstore/fulcio/pkg/api [build failed]
```

This is due to two dependencies referencing an old buggy version of the https://github.com/miekg/pkcs11 library:

* https://github.com/ThalesIgnite/crypto11 - fixed by https://github.com/ThalesIgnite/crypto11/pull/89
* https://github.com/containers/ocicrypt - fixed by https://github.com/containers/ocicrypt/pull/56

https://github.com/miekg/pkcs11/pull/140 fixes the issue in the upstream, and is available in miekg/pkcs11 v1.1.0 or newer.

**Comment by tstromberg** [comment]
It seems like running `go get github.com/miekg/pkcs11@v1.1.1` successfully fixes this problem, so I will raise an appropriate PR for it.

**Comment by dlorenc** [comment]
Let's use this to also track adding a presubmit test somehow to make sure this still compiles!
