### ISSUE TITLE
Create a simple RFC process for important changes

### ISSUE THREAD

**Issue by nsmith5** [sigstore/fulcio#379]
**Description**

Sometimes, we there is a need to propose a change to Fulcio requires more space, discussion and scrutiny than Github issues is good for. I believe these change proposals should be both documented once accepted and placed under the code review process for acceptance.

Two examples of such changes I can think off right now are the refactor of are #275 and #304. The are big enough that no single PR should seek to implement the whole thing, but I think as a project we should go through the RFC process to discuss what we'd like it to look like once completed.

We often see Google docs etc floating about for this purpose, but they're not very discoverable once complete.

**Comment by haydentherapper** [comment]
Discussion in community for this issue, closing.
