### ISSUE TITLE
Fulcio returns 200 if there's no RootCert

### ISSUE THREAD

**Issue by vaikas** [sigstore/fulcio#415]
**Description**

Calling Fulcio to fetch rootCert returns 200 even if there's an error, it's just logged. 
https://github.com/sigstore/fulcio/blob/main/pkg/api/ca.go#L242

This looks to caller like things worked, but then they'd have to verify the output in addition to error checking. We should return an error to the caller.

/assign vaikas

**Comment by nsmith5** [comment]
Oh dear yeah there is no status setting anywhere there. There should also be a return statement under all the error handling so so we trundle onward after hitting errrors
