### ISSUE TITLE
Deploy latest release to fulcio.sigstore.dev, decide plan for v1.fulcio.sigstore.dev

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/fulcio#428]
cc @bobcallaway @dlorenc 

I was testing out `/api/v1/rootCert` and realized there were recent changes missing on `v1.fulcio.sigstore.dev`. `fulcio.sigstore.dev` still uses the beta GCP CA Service instance, which should be turned down before GA. Can we deploy the latest release to `fulcio.sigstore.dev` and `v1.fulcio.sigstore.dev`? 

What should we do about the `v1` instance? Currently it's referenced by Cosign. I don't think we have any need for it. Can we switch over to using `fulcio.sigstore.dev` in Cosign, and after X number of releases, drop the v1 endpoint? Alternatively, we keep v1, and drop `fulcio.sigstore.dev`?

**Comment by haydentherapper** [comment]
@priyawadhwa - This is something we should decide before GA too

**Comment by haydentherapper** [comment]
@bobcallaway @dlorenc - Do y'all have thoughts on this? I'd like to get this sorted out before GA because of the breaking nature of this change. I'm thinking we one of the following:
1. Deploy the latest release to `fulcio.sigstore.dev` and `v1.fulcio.sigstore.dev`. This would remove the need for the original Fulcio root CA cert. Update Cosign to use `fulcio.sigstore.dev`. I'll use `cs.github.com` to find uses of `v1.fulcio.sigstore.dev` and get them switched over. Turn down `v1.fulcio.sigstore.dev` before Sigstore GA.
2. Keep `v1.fulcio.sigstore.dev` exclusively, turning down `fulcio.sigstore.dev` before Sigstore GA. I'll try to find references to `fulcio.sigstore.dev` too.
3. Keep both, but just update `v1.fulcio.sigstore.dev`. I really don't like this idea because `fulcio.sigstore.dev` will not get bug fixes.

I'd prefer to go with (1). It doesn't make much sense to have `v1.foo.com/v1` in terms of versioning.

**Comment by dlorenc** [comment]
I think my original plan was to do something like 1, but then change the v1.fulcio.sigstore.dev hostname to point at the same backend as fulcio.sigstore.dev. That means there's no rush to update the code or ever really turn down the hostname.

**Comment by haydentherapper** [comment]
That sounds good with me. I can bring this change up at tomorrow's community meeting if that works. If code has pinned the Fulcio root to the original root, we can give folks a head's up that it'll be changing on `fulcio.sigstore.dev`.

**Comment by haydentherapper** [comment]
I brought this up in today's community meeting. @dlorenc or @bobcallaway, do you want to kick off the deployment from HEAD to both clusters? We just need to give a heads up on Slack before we do.

**Comment by haydentherapper** [comment]
This has been completed!
