### ISSUE TITLE
Capture the IDP somewhere in the cert

### ISSUE THREAD

**Issue by dlorenc** [sigstore/fulcio#44]
We should log **who** said the challenge was correct somewhere. So instead of just a cert issued to an email, we say "google validated the identity token", in case of an issue with the OIDC providers.

**Comment by dlorenc** [comment]
From @bobcallaway:

> we should record the "issuer" and the other claim that is the identifer for the identity


I'm not sure we should store the other one, I'll have to think about it. If multiple email addresses are tied to the same identifier, we probably don't want to track that.

**Comment by dlorenc** [comment]
Ah yeah - we can find a field for this or use our own OID.

**Comment by dlorenc** [comment]
ref #80 as well.

**Comment by raesene** [comment]
Just to expand on what my thought from Slack, what I was thinking about is the threat model where an attacker is able to register an e-mail address at one of the providers that a user doesn't have an account on, and then sign an artifact using that identity. 

Addressing this at a basic level seems like it needs a couple of things:

- The OIDC provider used to authenticate the user needs to be recorded at the time of the signing.
- The UI of the signing tool needs to display the provider alongside the validated e-mail address.
- The documentation needs to state that people who are signing artifacts should make it clear which provider(s) they are using for the process to their users, and also that people who want to verify a signature need to check that the combination of e-mail address and provider matches what was expected for that artifact.

**Comment by dlorenc** [comment]
Yeah!

**Comment by dlorenc** [comment]
For reference: https://github.com/sigstore/fulcio/pull/211
