### ISSUE TITLE
API improvement: Optionally provide lifetime of certificate

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/fulcio#474]
**Description**

Currently, Fulcio issues certificates with a lifetime of 10 minutes. Clients may want to further limit the lifetime of certificates. The smaller the window, the less risk for reuse of the certificate within its validity period. 

An optional API field could be added to allow callers to specify the lifetime of the certificate. The requested lifetime would be truncated if it's longer than Fulcio's maximum lifetime (10 minutes).

**Comment by haydentherapper** [comment]
cc @asraa @bobcallaway

**Comment by dlorenc** [comment]
I like it!

**Comment by asraa** [comment]
+1 for adding this!

**Comment by dlorenc** [comment]
It hasn't come up anywhere in a real use case so I'm fine closing it
