### ISSUE TITLE
fulcio client: json: cannot unmarshal object into Go value of type string

### ISSUE THREAD

**Issue by priyawadhwa** [sigstore/fulcio#48]
I'm trying to run fulcio locally with

```
go run ./cmd/server/ serve --port 5555 --gcp_private_ca_parent=projects/<project>/locations/<location>/certificateAuthorities/<name>
```
as described in [DEVELOPMENT.md](https://github.com/sigstore/fulcio/blob/development/config/DEVELOPMENT.md).

I'm able to get the server running, but running the client is failing with this bug:

```
$ go run ./cmd/client/
Your browser will now be opened to:
<browser url>
Error: json: cannot unmarshal object into Go value of type string
Usage:
  fulcio-client [flags]

Flags:
      --fulcio_address string       address of fulcio server (default "http://127.0.0.1:5555")
  -h, --help                        help for fulcio-client
      --oidc-client-id string       client ID for application (default "237800849078-rmntmr1b2tcu20kpid66q5dbh1vdt7aj.apps.googleusercontent.com")
      --oidc-client-secret string   client secret for application (default "CkkuDoCgE2D_CCRRMyF_UIhS")
      --oidc-issuer string          OIDC provider to be used to issue ID token (default "https://accounts.google.com")

2021/03/15 15:01:11 json: cannot unmarshal object into Go value of type string
exit status 1
```

Interestingly, it seems to pass with fulcio prod but fail with fulcio locally, so I'm guessing something was merged recently which broke this behavior. Seems like the error is coming from the call to `SigningCert`

https://github.com/sigstore/fulcio/blob/22a5bee83b6887f985fabc4de8fb2383539b3f77/cmd/client/app/root.go#L116

I'm checking it out right now, but opened an issue in case anybody might already know what's going on :)

**Comment by lukehinds** [comment]
I am pretty sure I got this when I never had gcloud auth to the certificate hosting service..let me double check

**Comment by priyawadhwa** [comment]
Thanks, I double checked the permissions and they should be valid. I  chatted with @dlorenc and he mentioned it might be because the ct log only allows certs signed by the real root CA!

**Comment by dlorenc** [comment]
Bob's #47 should make this error message much nicer

**Comment by priyawadhwa** [comment]
This has been resolved, closing!
