### ISSUE TITLE
Fulcio as an intermediate CA

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/fulcio#489]
[Design doc](https://docs.google.com/document/d/1QLTMgjX7n74PyNpp3SIxsH7vbak8k-EoylttR25gBXM/edit#heading=h.dgwm7wkem51s)

From the work to support embedded SCTs, coupled with a desire to be able to scale beyond 25 QPS, I've written up a doc on the work to reconfigure the production instance of Fulcio as an intermediate CA.

tl;dr - An in-memory signing key is generated on each server initialization. Fulcio requests an intermediate CA certificate from the managed GCP root, periodically refreshing it. This work involves adding a new CA implementation, which would be a combination of the ephemeral and file CAs.

This has many benefits:
* No outbound calls to create and sign certificates
* Ability to scale up QPS significantly
* Minimizes the risk of signing key leakage
* Automates the process of fetching intermediate CA certs (less operational overhead)

**Comment by k4leung4** [comment]
I found a similar issue, https://github.com/sigstore/fulcio/issues/28, should we close that one?
