### ISSUE TITLE
pkg/api/client.RootCert should use the provided *http.Client

### ISSUE THREAD

**Issue by imjasonh** [sigstore/fulcio#501]
**Description**

`RootCert` calls `http.Get`, which uses the default client:

https://github.com/sigstore/fulcio/blob/56c15d68101f8aa3d6376bd8da9993a27edcd0cd/pkg/api/client.go#L138

Contrast with `SigningCert`, which uses the provided `*http.Client` if one was provided:

https://github.com/sigstore/fulcio/blob/56c15d68101f8aa3d6376bd8da9993a27edcd0cd/pkg/api/client.go#L97

This means that if `WithTimeout` or `WithUserAgent` are called, these will be ignored when fetching the root cert. If future client options are added, these would likely also be ignored.

If this is unintentional, I can send a PR to fix it.

**Comment by imjasonh** [comment]
Looks like it was added in https://github.com/sigstore/fulcio/pull/290 cc @vaikas

**Comment by vaikas** [comment]
Oops, great call @imjasonh thanks! Are you sending a PR or do you want me to clean up my own messes? :)

**Comment by imjasonh** [comment]
> Oops, great call @imjasonh thanks! Are you sending a PR or do you want me to clean up my own messes? :)

I got you: https://github.com/sigstore/fulcio/pull/502
