### ISSUE TITLE
Adding Rekor OIDs?

### ISSUE THREAD

**Issue by wlynch** [sigstore/fulcio#563]
**Question**

Half question / half looking for feedback: do we have any sort of process for adding new [Sigstore OIDs](https://github.com/sigstore/fulcio/blob/main/docs/oid-info.md) (beyond just opening a PR)?

An idea I had recently was to add OIDs for classifying Rekor data in order to embed info in signatures that allow for ASN.1 identifiers (such as [PKCS7 attributes](https://datatracker.ietf.org/doc/html/rfc2315#section-9.2)). i.e.

```
1.3.6.1.4.1.57264.1.7 | Rekor URL

This contains the URL of the Rekor instance where signatures are written to. 
```

This could allow us to add data to signatures to point users to where the associated tlog entry is if they only have the signature to start - e.g.

1. Parse signature
2. Extract Rekor URL OID
3. Use associated value as Rekor API URL base
4. Look up signature in transparency log

This wouldn't necessarily be a value that Fulcio itself would ever set, so I'm not sure if this would make sense to put under the `1.3.6.1.4.1.57264.1` Fulcio root.

Open to feedback here (i.e. let me know if this is an awful idea 😅 )!

cc @dlorenc

**Comment by haydentherapper** [comment]
What would be the purpose of this? Is this just an optimization so the client doesn't need to know the Rekor log location?

I'd prefer that Fulcio and Rekor remain separate - Fulcio's job is associating an identity with a key, and Rekor's is witnessing an event. I don't think Fulcio should sign off on the location of the log entry - It's unverified metadata.

**Comment by haydentherapper** [comment]
Maybe I misread - Is this asking just generally about creating new OIDs, or including additional metadata in issued certificates?

**Comment by wlynch** [comment]
> What would be the purpose of this? Is this just an optimization so the client doesn't need to know the Rekor log location?

Yup! If you saw a signature and didn't know where the Rekor instance was, it could be a way to hint where to go.

> I'd prefer that Fulcio and Rekor remain separate - Fulcio's job is associating an identity with a key, and Rekor's is witnessing an event. I don't think Fulcio should sign off on the location of the log entry - It's unverified metadata.

> Maybe I misread - Is this asking just generally about creating new OIDs, or including additional metadata in issued certificates?

+1 to keeping fulcio and rekor separate - mainly inquiring about creating new OIDs / whether or not such an OID would be a bad idea (e.g. if the value was misleading, would this be a vector for abuse?)

I opened this question here since the fulcio repo is the only instance where these OIDs are defined. Happy to reopen this question elsewhere if there's a better place for it!

**Comment by haydentherapper** [comment]
We could create `1.3.6.1.4.1.57264.2` for Rekor. Ideally it shouldn't be misleading, OIDs should be unambiguous.

I'd be curious to see more about how you'd like to use OIDs! The tricky thing is they aren't the easiest to work with when it comes to client libraries. The other thing to consider is if the value is unsigned, there's an opportunity for a vulnerability - Say if you included the URL in the OCI manifest, but it was not signed, an attacker could replace the value of the OID with a reference to an attacker controlled log.

**Comment by wlynch** [comment]
Signature types like PKCS7 do allow for signed attributes! But thinking through this more I think your point still holds since signed doesn't necessarily mean trusted.  i.e. we may be able to verify a signed value, but we wouldn't be able to trust the public key until we reached out and verified it with the log itself, right? So in that case the value of this would be limited. 😞

**Comment by wlynch** [comment]
Sleeping on it, I think I'm sufficiently convinced we don't want this, so closing out.

Thanks for helping bounce ideas @haydentherapper! 😃
