### ISSUE TITLE
`make` command require `swagger` cli

### ISSUE THREAD

**Issue by endorama** [sigstore/fulcio#57]
Trying to run `make` produce an error due to `swagger` not being found.

```
$ make
swagger generate server -f openapi.yaml -q -r COPYRIGHT.txt -t pkg/generated --exclude-main -A fulcio_server --exclude-spec --flag-strategy=pflag -P github.com/coreos/go-oidc/v3/oidc.IDToken
make: swagger: Command not found
Makefile:10: recipe for target 'pkg/generated/models/%.go' failed
make: *** [pkg/generated/models/%.go] Error 127
```

I'm not sure how I'm supposed to install it, I'd like some guidance. Happy to improve the docs with a PR. 
Thanks!

**Comment by dlorenc** [comment]
Great point! There was some trickiness regarding exact versions before, but I'm not sure how much that matters now. Here's what our github actions code does to install it:

https://github.com/sigstore/fulcio/blob/development/.github/workflows/main.yml#L30

Does that work for you?

**Comment by endorama** [comment]
Yes thanks! Should I make a PR to amend the docs?

**Comment by dlorenc** [comment]
Sure, if you're up for it!
