### ISSUE TITLE
Cert Transparency

### ISSUE THREAD

**Issue by dlorenc** [sigstore/fulcio#6]
Fulcio will need to log certs to a CT log. Given our non-standard usecase, it probably makes sense for this to be a new one rather than an existing one (although a cert is a cert...). Has anyone given thought to this yet? We could run the log as part of rekor (same DB, different log) or a different service.

It will need a public API, probably https://tools.ietf.org/html/rfc6962

* https://<log server>/ct/v1/get-roots would return the root CA cert for fulcio itself
* https://<log server>/ct/v1/add-chain would be the call to add a new entry
...

**Comment by lukehinds** [comment]
I was guessing this could be handled by types and some of the x509 code there, so like you say, same rekor, but a different tree / DB.

**Comment by lukehinds** [comment]
edit: alongside the additional handlers.

**Comment by lukehinds** [comment]
closed from https://github.com/sigstore/fulcio/commit/b2b05a00f104c580bd0ecb44889dfb6d371eb857
