### ISSUE TITLE
building fulcio server complains about missing go.sum in github.com/coreos/go-oidc/v3/oidc 

### ISSUE THREAD

**Issue by endorama** [sigstore/fulcio#62]
After #57 trying to build the project I encountered an error:

```
$ make
swagger generate server -f openapi.yaml -q -r COPYRIGHT.txt -t pkg/generated --exclude-main -A fulcio_server --exclude-spec --flag-strategy=pflag -P github.com/coreos/go-oidc/v3/oidc.IDToken
swagger generate client -f openapi.yaml -q -r COPYRIGHT.txt -t pkg/generated -P github.com/coreos/go-oidc/v3/oidc.IDToken
go build ./cmd/server
pkg/generated/restapi/configure_fulcio_server.go:30:2: missing go.sum entry needed to verify package github.com/coreos/go-oidc/v3/oidc (imported by github.com/sigstore/fulcio/pkg/generated/restapi) is provided by exactly one module; to add:
	go get github.com/sigstore/fulcio/pkg/generated/restapi
Makefile:24: recipe for target 'server' failed
make: *** [server] Error 1
```

Easy workaround is to run the provided command (`go get github.com/sigstore/fulcio/pkg/generated/restapi`) but I was wondering if this is expected or should be fixed.

I'm a bit confused about go getting part of the package I'm trying to build locally and what side effects this may produce.

**Comment by dlorenc** [comment]
Yeah that is strange. What version of go are you using? I know a lot has changed here in Go 1.16.

**Comment by endorama** [comment]
I'm using `1.15.10`. I tried cleaning the package with `go clean -i` but the error now does not show up anymore. Any idea how can I revert go packages to the status before the `go get` (other than `go clean`)?

**Comment by dlorenc** [comment]
> Any idea how can I revert go packages to the status before the `go get` (other than `go clean`)?

Whoa, no idea. I didn't even know there was a `go clean` command!

**Comment by endorama** [comment]
So I'm not able to reproduce this anymore to find the cause or troubleshoot it.

Feel free to close it then and thanks for the help.

**Comment by dlorenc** [comment]
Thanks for trying!
