### ISSUE TITLE
Define certificate semantics

### ISSUE THREAD

**Issue by dlorenc** [sigstore/fulcio#65]
Basically, resolve my TODO here: https://github.com/sigstore/fulcio/blob/development/pkg/ca/ca.go#L63

We should write this up into a basic spec.

- What fields must be set for something to be a valid code signing cert by sigstore clients
- How does expiry work?
- What "timestamp" proofs are acceptable?
- How does chain validation work? What can intermediate certs do?

And probably much more!

I know @mmalone talked about this a bit in slack, but can't remember if we got an issue filed somewhere.

**Comment by haydentherapper** [comment]
Closing, all of these have been decided
