### ISSUE TITLE
Browserless  OIDC authentication flow

### ISSUE THREAD

**Issue by fredcsfaria** [sigstore/fulcio#672]
**Question**

 
Is there any way to do the authentication with OIDC  without needing to use a browser  ?

**Comment by fredcsfaria** [comment]
Hello ,
   
   - Which identity provider are you wanting to authenticate against?
GitHub/Google

   
   - Can you describe your use case (e.g. why would a browser not be available or desirable)?
We have some remote  linux dev  environments  with no GUI support  due to company governance/security policies.   

    Em quarta-feira, 6 de julho de 2022 09:06:10 BRT, Bob Callaway ***@***.***> escreveu:  
 
 


Hi - could I ask a couple questions to help me scope the answer to your question appropriately:
   
   - Which identity provider are you wanting to authenticate against?
   - Can you describe your use case (e.g. why would a browser not be available or desirable)?

**Comment by bobcallaway** [comment]
We will be re-enabling device flow support soon, which will allow you to copy and paste a code into a system that does have a browser to drive the authentication flow forward according to https://datatracker.ietf.org/doc/html/rfc8628.

**Comment by bobcallaway** [comment]
This needs to merge: https://github.com/sigstore/sigstore/pull/602 and have a release cut with it in it

Cosign then needs to adopt the updated call, and we need to rollout an updated version of Dex (based on v2.33.0) into staging.

**Comment by haydentherapper** [comment]
Closing as device flow has been enabled.
