### ISSUE TITLE
Should we move cosign's cert verification / policy checks to fulcio repo?

### ISSUE THREAD

**Issue by wlynch** [sigstore/fulcio#676]
**Question**

I found out recently that the policy-controller has a dependency on cosign in order to use it's Fulcio certificate verification - 
https://github.com/sigstore/policy-controller/blob/05108e3476df8d9078d7cbc3d181f0060dd23df8/pkg/webhook/validation.go#L111-L116

A good chunk of this appears to be Fulcio cert validation: 
https://github.com/sigstore/cosign/blob/a4cb262dc3d45a283a6a7513bb767a38a2d3f448/pkg/cosign/verify.go#L162-L264

In the spirit of trying to break out common pieces from cosign so that they can be used by other components, I'm wondering if we should move the cert validation / policy checking to the fulcio repo (or sigstore/sigstore). Are people in favor of this, or do we think that policy checking is too client specific that it doesn't make sense? 🤔 

Let me know what you think!

**Comment by wlynch** [comment]
cc @imjasonh

**Comment by imjasonh** [comment]
We could also have this expressed in Fulcio as "extract useful stuff from the cert" (emails, etc) and have it return those for cosign, policy-controller, etc., to verify against whatever policies. If the cert is invalid, `fulcio.ExtractStuff` returns an `err`.

That's sort of what `ValidateAndUnpackCert` sounds like it does already, it just "unpacks" it and immediately checks it against `CheckOpts`.

**Comment by haydentherapper** [comment]
I'm happy to have this moved out of Cosign and into Fulcio. A `client` package would be helpful.

I'd prefer it live in Fulcio, rather than sigstore/sigstore. I'm not certain we know exactly what should live in sigstore/sigstore, and I'd worry it'll slowly turn into Cosign V2 if we just start moving everything out.

**Comment by lukehinds** [comment]
sigstore/sigstore is the prefered home, as in the past we have made efforts to keep client code outside of rekor / fulcio and instead utilise sigstore/sigstore.

sigstore/sigstore, would be better titled as sigstore/sigstore-go (like sigstore-rs, sigstore-python), but go is a mess when it comes to renames.

**Comment by haydentherapper** [comment]
One concern with this is it'd be best if the maintainers of the respective repositories had ownership of this logic and visibility into changes to this logic. Those who maintain Rekor are most likely to understand the tlog verification flow, and for Fulcio understanding the certificate verification flow.

**Comment by znewman01** [comment]
I agree in principle that `sigstore/sigstore` is the right place. However, there's an issue in my mind: `sigstore/sigstore` conflates two roles: (1) common code for the Sigstore services, and (2) a Sigstore Golang client.

These make it pretty hard to disentangle what goes where. I'd expect a client library to take a dependency on `sigstore/fulcio` and `sigstore/rekor` (for the protos, at least), but `sigstore/sigstore` contains code that gets used inside of Fulcio/Rekor.

 I believe this is some of the reason for the confusion about where things live: it's hard to move these checks into `sigstore/sigstore` even though they "belong" to Fulcio and often will need to be updated in sync with it; doing the "right thing" and putting all client logic into `sigstore/sigstore` thus has a pretty big coordination cost (simple changes involve a change to `sigstore/sigstore` and then a version bump/corresponding change in the downstream service).

> I'm not certain we know exactly what should live in sigstore/sigstore, and I'd worry it'll slowly turn into Cosign V2 if we just start moving everything out.

I think there's actually a pretty clear dividing line between a `sigstore-go` and `cosign`: anything container/OCI related, or CLI related belongs in Cosign, but Cosign itself should be a relatively thin wrapper. This is aspirational and certainly not the status quo today.

>  One concern with this is it'd be best if the maintainers of the respective repositories had ownership of this logic and visibility into changes to this logic. Those who maintain Rekor are most likely to understand the tlog verification flow, and for Fulcio understanding the certificate verification flow.

Agreed, but in the longer term as more clients *aren't* using Golang, we need a better system here than "use these libraries and you'll get updates." This might looks like the in-progress specification docs 😄

**Comment by haydentherapper** [comment]
Closing - sigstore-go is the place for verification logic going forward
