### ISSUE TITLE
fulcio.sigstore.dev is not working

### ISSUE THREAD

**Issue by creeper-0910** [sigstore/fulcio#723]
**fulcio.sigstore.dev is not working**

It appears that fulcio.sigstore.dev returns a 404 when accessed.
Instructions for using the tuf-client in the README can be found at https://raw.githubusercontent.com/sigstore/root-signing/main/repository/repository/~
is not available due to broken links in

**Comment by haydentherapper** [comment]
Are you trying to access the instance’s certificate chain? It is available at https://fulcio.sigstore.dev/api/v2/trustBundle.

**Comment by haydentherapper** [comment]
Note that fulcio.sigstore.dev does return a 404 as expected, nothing is served from that URL. See the [proto definition](https://github.com/sigstore/fulcio/blob/main/fulcio.proto) for available methods. 

As for TUF, the Fulcio certificate chain is securely provided in the TUF repository. If you're using Sigstore, this is handled automatically, or with `cosign initialize.` 

Feel free to ping the issue if you have other questions.
