### ISSUE TITLE
Usage outside of sigstore

### ISSUE THREAD

**Issue by letmaik** [sigstore/fulcio#95]
The fulcio client code recently moved from this repo to the sigstore cli in the sigstore repo. I think fulcio is useful on its own as well, independently of rekor. The sigstore cli (correct me if I'm wrong) currently doesn't allow to just retrieve a fulcio cert without signing and sending to rekor. 

Is fulcio intended to stay as an independent service? If so, does it make sense to have a stand-alone client here (or elsewhere) for it? Or alternatively extend the sigstore cli to retrieve a cert for custom usage?

**Comment by dlorenc** [comment]
Hey @letmaik! Great question. We can certainly put the command line client back here if you find it useful. The move was mainly about code organization and to prevent cycles, we want all shared logic to live in sigstore/sigstore.

Fulcio could certainly import that back here and ship a standalone CLI if it makes sense to you. Just curious - what use cases do you have in mind?

**Comment by lukehinds** [comment]
sigstore/sigstore is the generic framework that other go-clients can utilise, for example cosign imports from sigstore. The reason for this is we ended up having duplicated code in different clients all inheriting from the server code (which should not really have client code). 

The issue with decoupling fulcio from the tlogs, is you lose trust guarantees  and accountability around fulcio. What did you have in mind if fulcio was standalone?

**Comment by letmaik** [comment]
I don't want to decouple fulcio from its certificate tlog (CT log), only from the artifact tlog. The main motivation is that different kinds of tlogs (not just rekor) may be used in combination with fulcio.

**Comment by dlorenc** [comment]
What type of command-line API are you imagining? It's a bit tricky if we assume the keys are always in memory. The 10m expiry does give some flexibility here for keys on disk. Something like:

```shell
$ <something to generate a keypair and write it to /tmp/key.pub|key.priv on a memoryfs>
# Get a certificate using the private key (to extract the public key and sign the challenge)
$ fulcio cert -key key.priv > cert.pem
```

Where the `fulcio cert` command would do the normal OIDC flow and add the cert to the CTFE log?

I think the other missing piece would be a TSA to make sure you used the private key when the cert was valid, but you could use any RFC3161 system for that.

**Comment by letmaik** [comment]
Yes, this makes sense to me. That's the kind of interface I was looking for. I guess you would print all diagnostic messages including the OIDC URL to stderr in this case.

Regarding TSA, good point, or alternatively something similar to what rekor is doing. If I understand rekor correctly, then for a client to validate an artifact signature it must also have the inclusion proof for the rekor log, as the client would trust that rekor checked the certificate validity period during submission.

**Comment by dlorenc** [comment]
Cool! Yeah this sounds like a useful addition. The client code that was in here was really just for testing and didn't actually even give users a way to get the private key before disposing of it, which is the main reason it was removed as part of the refactor.

Is this something you're interested in contributing?

Re: rekor - that's close-ish. Rekor doens't check the cert timestamp, but the signed inclusion proof **does** include the timestamp that rekor originally witnessed the entry at. Rekor will also expose a traditional RFC3161 server as part of https://github.com/sigstore/rekor/pull/293 and probably a simpler JSON version too.

**Comment by lukehinds** [comment]
I guess we could have a `-no-rekor` flag and wrap a conditional around the rekor http client POST.

**Comment by dlorenc** [comment]
> I guess we could have a `-no-rekor` flag and wrap a conditional around the rekor http client POST.

I don't think we would need it - if `fulcio-cli` acts on existing keys and retrieves certificates, nothing is actually generating signatures so we'd have nothing to upload to rekor anyway. You could always chain a pipeline together:

1. make a keypair with openssl or something
2. use `fulcio-cli` to get a cert
3. Sign something with the key from step 1 using openssl or something
4. Use rekor-cli to upload to rekor

**Comment by letmaik** [comment]
@dlorenc I think this flow makes sense. The stand-alone client would probably be needed as well with https://github.com/sigstore/fulcio/issues/84, where you would use fulcio just to provision the signing cert, and the actual signing will happen at a later point in time.

**Comment by dlorenc** [comment]
Awesome! Let me know if you want to take this on, I'm happy to help get it merged!

**Comment by lukehinds** [comment]
@mbestavros is going to work on this

I wonder if this should be on it's own sigstore/fulcio-cli , I say this in consideration that we just refactored all the client code out, so I would like to keep to that state of play.

**Comment by mbestavros** [comment]
I've opened a PR with my first stab at this here: https://github.com/sigstore/fulcio/pull/123 -- feedback welcome!

**Comment by lukehinds** [comment]
closing , open again if needed.
