### ISSUE TITLE
AKS issuer URL is different from configured format

### ISSUE THREAD

**Issue by yorinasub17** [sigstore/fulcio#970]
**Description**

It appears that AKS has updated the OIDC Issuer URL format and it no longer matches what Fulcio expects. The AKS cluster that I have running in the East US region has the following OIDC Issuer URL for the workload identity preview:

```
%~> az aks show -n myCluster -g myGroup --query "oidcIssuerProfile.issuerUrl" -otsv
The behavior of this command has been altered by the following extension: aks-preview
https://eastus.oic.prod-aks.azure.com/****
```

This may also be a difference in the specific region that the AKS cluster is provisioned in.

**Version**

cosign: v2.0.0-rc.0
fulcio: Public instance (`https://fulcio.sigstore.dev`)

**Comment by haydentherapper** [comment]
@yorinasub17 Do you want to try now, https://fulcio.sigstore.dev/api/v2/configuration shows it should be rolled out

**Comment by yorinasub17** [comment]
Just tried and it worked! I was able to successfully get a signing certificate from `fulcio` using `cosign`! Many thanks for the review and help getting this rolled out!
