### ISSUE TITLE
Failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ivanayov** [sigstore/fulcio#980]
**Description**
 
I'm not sure if it's a bug, but find it good to report in case it is.

I followed those steps to try out Fulcio:

```
$ export COSIGN_EXPERIMENTAL=1

$ echo "test file contents" > test-file.txt

$ cosign sign-blob test-file.txt --output-certificate  fulcio.crt.base64 --output-signature fulcio.sig

## verified via GitHub and got
... Successfully verified SCT...
    using ephemeral certificate:
    ...

$ base64 -d < fulcio.crt.base64 > fulcio.crt

$ step certificate inspect fulcio.crt

## got certificate output

$ step certificate verify fulcio.crt --roots  ~/.sigstore/root/targets/fulcio_v1.crt.pem

```

And it failed with:

```
failed to verify certificate: x509: certificate signed by unknown authority
```

**Version**

Cosign version: 1.13.1
Smallstep CLI/0.23.1 (darwin/amd64)

**Comment by haydentherapper** [comment]
The public good instance of Fulcio uses an intermediate `fulcio_intermediate_v1.crt.pem` and root certificate `fulcio_v1.crt.pem`. If I recall, `step certificate verify` doesn't support verification with intermediates, but I would confirm with them.

You can also verify with openssl: `openssl verify -CAFile fulcio_v1.crt.pem -untrusted fulcio_intermediate_v1.crt.pem fulcio.crt`
